spring:
  application:
    name: quill-api
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_quill
    default-schema: public

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

imagekit:
  url-endpoint: ${IMAGEKIT_URL_ENDPOINT}
  public-key: ${IMAGEKIT_PUBLIC_KEY}
  private-key: ${IMAGEKIT_PRIVATE_KEY}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

security:
  jwt:
    secret: ${JWT_SECRET}