cors:
  allowedOrigins:
    - http://localhost:3000

logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: quill-api
  datasource:
    url: jdbc:postgresql://localhost:5432/quill
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_quill
    default-schema: public

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect