spring:
  application:
    name: quill-api
  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_quill
    default-schema: public

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect